---
ID: "c531f7bc-e4b6-465c-b6b9-52e8bf1f41df"
Parent: "564f95e8-0f69-4a42-b74e-5501ae4ad1e7"
Template: "564f95e8-0f69-4a42-b74e-5501ae4ad1e7"
Path: /sitecore/templates/Project/PLAY/Rendering Parameters/Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ee67f893-2ef0-4037-b616-26510014b48c"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d0cd2af5-a7b5-4fdd-befd-057721bbac1b"
